# Generated by Django 6.0.6 on 2026-07-07 09:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_menupagedocument_created_at_menupageimage_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=255)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('document', 3), ('link', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'icon': 'doc-full'}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5), ('url', 6)]], {'icon': 'link'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
