# Generated by Django 6.0.6 on 2026-07-07 09:45

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_manualpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPageManualResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('document', 3), ('link', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'icon': 'doc-full'}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5), ('url', 6)]], {'icon': 'link'})})),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_resources', to='home.menupage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ManualPage',
        ),
    ]
