# Generated by Django 6.0.6 on 2026-07-07 10:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_menupagemanualresource_delete_manualpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupagemanualresource',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 3), ('document', 4), ('link', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media'}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'icon': 'doc-full'}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 7: ('wagtail.blocks.URLBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('description', 6), ('url', 7)]], {'icon': 'link'})}),
        ),
    ]
