# Generated by Django 6.0.6 on 2026-07-09 20:17

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_menupagemanualresource_body'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ErrorReportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.CharField(blank=True, help_text='Rezumat scurt al situatiei/erorii.', max_length=255)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 3), ('video_upload', 4), ('document', 5), ('link', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pentru YouTube, Vimeo sau alte linkuri embed suportate.', 'icon': 'media', 'label': 'Video link'}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Pentru fisiere video incarcate in Documents.', 'icon': 'media', 'label': 'Video upload'}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'icon': 'doc-full'}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 7), ('url', 8)]], {'icon': 'link'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FAQEntryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 3), ('video_upload', 4), ('document', 5), ('link', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pentru YouTube, Vimeo sau alte linkuri embed suportate.', 'icon': 'media', 'label': 'Video link'}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Pentru fisiere video incarcate in Documents.', 'icon': 'media', 'label': 'Video upload'}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'icon': 'doc-full'}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 7), ('url', 8)]], {'icon': 'link'})})),
                ('is_answered', models.BooleanField(default=False, help_text='Bifeaza cand intrebarea a primit un raspuns clar.', verbose_name='Raspuns oferit')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FAQIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PersonalSpaceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PersonalSpacePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 3), ('video_upload', 4), ('document', 5), ('link', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pentru YouTube, Vimeo sau alte linkuri embed suportate.', 'icon': 'media', 'label': 'Video link'}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Pentru fisiere video incarcate in Documents.', 'icon': 'media', 'label': 'Video upload'}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'icon': 'doc-full'}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 7), ('url', 8)]], {'icon': 'link'})})),
                ('owner_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='personal_space_page', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
