# Generated by Django 6.0.6 on 2026-07-10 18:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_grup_angajati_permisiuni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalspacesection',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('video', 2), ('link', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pentru YouTube, Vimeo sau alte linkuri embed suportate.', 'icon': 'media', 'label': 'Video link'}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('title', 3), ('description', 4), ('url', 5)]], {'icon': 'link'})}),
        ),
    ]
