# Generated by Django 6.0.6 on 2026-07-10 19:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_consolidare_permisiuni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalspacesection',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 3), ('video_upload', 4), ('document', 5), ('link', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pentru YouTube, Vimeo sau alte linkuri embed suportate.', 'icon': 'media', 'label': 'Video link'}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Pentru fisiere video incarcate in Documents.', 'icon': 'media', 'label': 'Video upload'}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'icon': 'doc-full'}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 7), ('url', 8)]], {'icon': 'link'})}),
        ),
    ]
