# Generated by Django 6.0.6 on 2026-08-03 11:18

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_redenumire_gestiune_facturare'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterCompatibilityPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CashRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model_name', models.CharField(max_length=150, verbose_name='Model')),
                ('compatible_cloud', models.BooleanField(default=False, verbose_name='Cloud')),
                ('compatible_cloud_android', models.BooleanField(default=False, verbose_name='Cloud Android')),
                ('compatible_pos_windows', models.BooleanField(default=False, verbose_name='POS Windows')),
                ('compatible_pos_android', models.BooleanField(default=False, verbose_name='POS Android')),
                ('errors_url', models.URLField(blank=True, help_text='URL-ul paginii cu erorile comune pentru aceasta marca (completat manual).', verbose_name='Link erori comune')),
                ('guide_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Ghid (document)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_rows', to='home.cashregistercompatibilitypage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
