# Generated by Django 6.0.6 on 2026-08-03 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_populare_case_de_marcat'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregistermodel',
            name='guide_document',
        ),
        migrations.AddField(
            model_name='cashregistermodel',
            name='guide_cloud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Ghid Cloud'),
        ),
        migrations.AddField(
            model_name='cashregistermodel',
            name='guide_cloud_android',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Ghid Cloud Android'),
        ),
        migrations.AddField(
            model_name='cashregistermodel',
            name='guide_pos_android',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Ghid POS Android'),
        ),
        migrations.AddField(
            model_name='cashregistermodel',
            name='guide_pos_windows',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Ghid POS Windows'),
        ),
    ]
