# Generated by Django 6.0.6 on 2026-08-07 03:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_cashregistermodel_guide_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreportpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 4), ('video', 5), ('video_upload', 6), ('document', 7), ('link', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Mic'), ('medium', 'Mediu'), ('full', 'Lat (toata coloana)')], 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('size', 3)]], {'icon': 'image'}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pentru YouTube, Vimeo sau alte linkuri embed suportate.', 'icon': 'media', 'label': 'Video link'}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Pentru fisiere video incarcate in Documents.', 'icon': 'media', 'label': 'Video upload'}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'icon': 'doc-full'}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 10: ('wagtail.blocks.URLBlock', (), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 8), ('description', 9), ('url', 10)]], {'icon': 'link'})}),
        ),
        migrations.AlterField(
            model_name='faqentrypage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 4), ('video', 5), ('video_upload', 6), ('document', 7), ('link', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Mic'), ('medium', 'Mediu'), ('full', 'Lat (toata coloana)')], 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('size', 3)]], {'icon': 'image'}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pentru YouTube, Vimeo sau alte linkuri embed suportate.', 'icon': 'media', 'label': 'Video link'}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Pentru fisiere video incarcate in Documents.', 'icon': 'media', 'label': 'Video upload'}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'icon': 'doc-full'}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 10: ('wagtail.blocks.URLBlock', (), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 8), ('description', 9), ('url', 10)]], {'icon': 'link'})}),
        ),
        migrations.AlterField(
            model_name='menupagemanualresource',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 4), ('video', 5), ('video_upload', 6), ('document', 7), ('link', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Mic'), ('medium', 'Mediu'), ('full', 'Lat (toata coloana)')], 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('size', 3)]], {'icon': 'image'}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pentru YouTube, Vimeo sau alte linkuri embed suportate.', 'icon': 'media', 'label': 'Video link'}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Pentru fisiere video incarcate in Documents.', 'icon': 'media', 'label': 'Video upload'}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'icon': 'doc-full'}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 10: ('wagtail.blocks.URLBlock', (), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 8), ('description', 9), ('url', 10)]], {'icon': 'link'})}),
        ),
        migrations.AlterField(
            model_name='personalspacesection',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 4), ('video', 5), ('video_upload', 6), ('document', 7), ('link', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Mic'), ('medium', 'Mediu'), ('full', 'Lat (toata coloana)')], 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('size', 3)]], {'icon': 'image'}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pentru YouTube, Vimeo sau alte linkuri embed suportate.', 'icon': 'media', 'label': 'Video link'}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Pentru fisiere video incarcate in Documents.', 'icon': 'media', 'label': 'Video upload'}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'icon': 'doc-full'}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 10: ('wagtail.blocks.URLBlock', (), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 8), ('description', 9), ('url', 10)]], {'icon': 'link'})}),
        ),
    ]
