# Generated by Django 6.0.6 on 2026-08-07 03:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_errorreportpage_body_alter_faqentrypage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreportpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('video', 6), ('video_upload', 7), ('document', 8), ('link', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Mic'), ('medium', 'Mediu'), ('full', 'Lat (toata coloana)')], 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Stanga'), ('center', 'Centru'), ('right', 'Dreapta')], 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('size', 3), ('align', 4)]], {'icon': 'image'}), 6: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pentru YouTube, Vimeo sau alte linkuri embed suportate.', 'icon': 'media', 'label': 'Video link'}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Pentru fisiere video incarcate in Documents.', 'icon': 'media', 'label': 'Video upload'}), 8: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'icon': 'doc-full'}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 11: ('wagtail.blocks.URLBlock', (), {}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('description', 10), ('url', 11)]], {'icon': 'link'})}),
        ),
        migrations.AlterField(
            model_name='faqentrypage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('video', 6), ('video_upload', 7), ('document', 8), ('link', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Mic'), ('medium', 'Mediu'), ('full', 'Lat (toata coloana)')], 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Stanga'), ('center', 'Centru'), ('right', 'Dreapta')], 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('size', 3), ('align', 4)]], {'icon': 'image'}), 6: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pentru YouTube, Vimeo sau alte linkuri embed suportate.', 'icon': 'media', 'label': 'Video link'}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Pentru fisiere video incarcate in Documents.', 'icon': 'media', 'label': 'Video upload'}), 8: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'icon': 'doc-full'}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 11: ('wagtail.blocks.URLBlock', (), {}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('description', 10), ('url', 11)]], {'icon': 'link'})}),
        ),
        migrations.AlterField(
            model_name='menupagemanualresource',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('video', 6), ('video_upload', 7), ('document', 8), ('link', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Mic'), ('medium', 'Mediu'), ('full', 'Lat (toata coloana)')], 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Stanga'), ('center', 'Centru'), ('right', 'Dreapta')], 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('size', 3), ('align', 4)]], {'icon': 'image'}), 6: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pentru YouTube, Vimeo sau alte linkuri embed suportate.', 'icon': 'media', 'label': 'Video link'}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Pentru fisiere video incarcate in Documents.', 'icon': 'media', 'label': 'Video upload'}), 8: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'icon': 'doc-full'}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 11: ('wagtail.blocks.URLBlock', (), {}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('description', 10), ('url', 11)]], {'icon': 'link'})}),
        ),
        migrations.AlterField(
            model_name='personalspacesection',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('video', 6), ('video_upload', 7), ('document', 8), ('link', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Mic'), ('medium', 'Mediu'), ('full', 'Lat (toata coloana)')], 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Stanga'), ('center', 'Centru'), ('right', 'Dreapta')], 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('size', 3), ('align', 4)]], {'icon': 'image'}), 6: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pentru YouTube, Vimeo sau alte linkuri embed suportate.', 'icon': 'media', 'label': 'Video link'}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Pentru fisiere video incarcate in Documents.', 'icon': 'media', 'label': 'Video upload'}), 8: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'icon': 'doc-full'}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 11: ('wagtail.blocks.URLBlock', (), {}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('description', 10), ('url', 11)]], {'icon': 'link'})}),
        ),
    ]
